### ISSUE TITLE
Alternate waypoint form in data not handled

### ISSUE THREAD

**Issue by TimBarham** [david-r-edgar/google-maps-data-parameter-parser#4]
Hey David... not sure if you're maintaining this anymore 🙂, but I'm using Gmdp for [WaypointGuru](https://waypoint.guru) and a user reported a problem with a Google Maps URL in the following form: 

https://www.google.com.au/maps/dir/-27.1111111,152.1111111/5+Meilland+Ct,+Eatons+Hill+QLD+4037/@-27.4273895,152.8739712,11z/data=!4m11!4m10!1m1!4e1!1m5!1m1!1s0x6b93fdbf3dfd303d:0xd5a53aa01525f506!2m2!1d152.9460143!2d-27.3346106!3e0!5i1

You'll note the first waypoint's coords are defined in the list of waypoint names at the start, and in the data parameter simply as "4e1", which Gmdp doesn't recognize as a waypoint.

**Comment by david-r-edgar** [comment]
Hi Tim, thanks for this.
If I'm understanding this correctly, it looks to me that this `4e1` is basically a placeholder for a waypoint which has no coords specified (in the protocol buffer, anyway)?
Looks like the only thing we can do is simply push a new 'undefined, undefined' waypoint. I'll look into doing that.

**Comment by TimBarham** [comment]
Yep, that was my interpretation (and agree that seems like the only reasonably fix). In my case, when I encounter an undefined waypoint like that, I pick up the coords from the list of names (which is where it always seems to be in such a scenario). The "undefined" waypoint at least means there are the correct number of waypoints. Thanks!
